#
# Makefile for the dsp driver depends on hardware
#

ifeq ($(CONFIG_SOC_EXYNOS9830_EVT0),y)
obj-$(CONFIG_EXYNOS_DSP_EXYNOS9830)	+= exynos9830_evt0/
else
obj-$(CONFIG_EXYNOS_DSP_EXYNOS9830)	+= exynos9830/
endif
